### ISSUE TITLE
Could not locate that visualization (id: BRFSS:-Respondents)

### ISSUE THREAD

**Issue by osat** [elastic/examples#179]
![screenshot from 2017-10-30 15-32-57](https://user-images.githubusercontent.com/32059857/32165097-a3c938e0-bd87-11e7-8737-00818cc2d14a.png)
After uploading the data into elasticsearch, I'm unable to see the visualization in the kibana dashboard. For every element in the dashboard I get this error with different id not being located. 
![screenshot from 2017-10-30 15-15-48](https://user-images.githubusercontent.com/32059857/32165051-7a26534c-bd87-11e7-936c-ddfa3522790e.png)

**Comment by gingerwizard** [comment]
@osat Can you confirm the version of Kibana you are using?

**Comment by gingerwizard** [comment]
I will try and reproduce this on kibana 5.6.3, updating the saved objects if required.

**Comment by gingerwizard** [comment]
I'm not able to reproduce this in 5.6.3. When importing the dashboards into 5.6.3, i am prompted to select the index pattern - at this point you should select `brfss` as shown below:

![image](https://user-images.githubusercontent.com/12695796/32450697-c67689c6-c30c-11e7-935a-aeefab9f4a63.png)

Otherwise no issues. @osat did you see any errors on import of the dashboards? Did you create the index pattern prior to the import?

**Comment by gingerwizard** [comment]
I've updated the example with this https://github.com/elastic/examples/pull/183 to illustrate this has been tested on 5.6.3

**Comment by gingerwizard** [comment]
@osat happy to reopen if you can provide reproducible steps on 5.6.3 or later.
