### ISSUE TITLE
ELKv2_docker_setup

### ISSUE THREAD

**Issue by rudijs** [elastic/examples#30]
Hi,

The ELK_docker_setup example I contributed previously targets vesion 1.x of both Logstash and Elasticsearch.

With 2.x released for both LS and ES now, I can contribute another example that targets these releases.

The ELKv2_docker_setup is very similar to v1.x but does have slight configuration changes in ES.

What would also be different in this new example is demonstrated use of tagged docker images, which makes it easy to set the exact versions of the 3 pieces (ELK) you wish to deploy.

If I contribute this new example I suggest perhaps keeping them both and renaming to something like:

ELKv1_docker_setup
ELKv2_docker_setup

Let me know if you'd like me to proceed.

Thanks.

**Comment by asawariS** [comment]
Hi Rudi, 

Yes, I think a new example would be great. However, instead of creating 2 folders under the examples/ repo, I would suggest have a examples/ELK_docker_setup/ and then have v1 and v2 subfolders under it. Hope that makes sense. 

Go ahead and create a PR for the content, and I will merge it in. 

Thanks!

**Comment by rudijs** [comment]
Hi,

@asawariS Sorry for the delay, version 2 ELK docker tutorial is ready for review and merge when all good.

PR sent.

Thanks.
